SET LINESIZE 80
SET PAGESIZE 60


SET FEEDBACK OFF
TTITLE CENTER 'EMPLOYEE REPORT' SKIP 1 CENTER 'As of ' _DATE
BTITLE CENTER 'Page:'SQL.PNO
BREAK ON job_id
COLUMN job_id  HEADING 'Job|Category' FORMAT A20
COLUMN Salary HEADING 'Salary' FORMAT $99,999.99
COLUMN Employees  FORMAT A30

-- 
SELECT job_id, last_name ||', '|| first_name AS Employees, salary
FROM HR.employees
WHERE salary > 5000
ORDER BY job_id, last_name;

SET FEEDBACK ON
CLEAR BREAK
COLUMN job_id CLEAR
COLUMN Employees CLEAR
COLUMN Salary CLEAR