INSERT INTO Game
(InventoryID, gameMode, Developers, Rating, Platform, Genre, Publishers, Themes,
Perspective, Description, Availablity, InventoryCount, CustomerID, Title)
VALUES
(2, 'SP/MP', 'Bungie STD', 97, 'Xbox', 'Adventure', 'Microsoft STD', 'Future', '1st Person', 'Play as Master Chief in this Classic', 'T', 5, 0001, 'Halo: Combat Evolved');

INSERT INTO PLATFORM
(PLATID, PLATNAME, PLATRATING, PLATDESC, PLATPRICE, INVENTORYID)
VALUES
( 2, 'Xbox', 80, 'DEVELOPED BY MICROSOFT', 50, 2);

INSERT INTO gameMode
(modeType, inventoryID)
VALUES
('SP/MP', 2);

INSERT INTO Developer
(DEVELOPER, DEVFIRST, DEVLAST, DEVCOMPANY, DEVDESC, INVENTORYID)
VALUES
('Bungie', 'JASON', 'JONES', 'BUNGIE STD', 'VIDEO GAME DESIGNER', 2);

INSERT INTO AVAILABLE
(AVAILGAME, INVENTORYID)
VALUES
('F', 2);

INSERT INTO PUBLISHERS
(PUBFIRST, PUBLAST, PUBDESC, INVENTORYID, DEVELOPER)
VALUES
('Bill', 'Gates', 'CEO OF MICROSOFT CORP', 2, 'Bungie');

INSERT INTO INVCOUNT
(COUNT, AVAILGAME)
VALUES
(5, 'T');

INSERT INTO GENRE
(GENRETYPE, PLATID)
VALUES
('Adventure', 2 );

INSERT INTO THEMES
(THEMETYPE, GENRETYPE)
VALUES
('Future', 'Adventure');

INSERT INTO DESCRIPTION
(DESCRIPT, DESCPUBLISHER, DESCDEVELOPER, DESCGAME, INVENTORYID, DEVELOPER, PUBFIRST)
VALUES
('Table of Information', 'CEO OF MICROSOFT CORP', 'VIDEO GAME DESIGNER', 'Play as Master Chief in this Classic', 2, 'Bungie', 'BILL' );

INSERT INTO Customer
(CUSTOMERID, CUSTOMERFNAME, CUSTOMERLNAME, CUSTOMERCC, CUSTOMERDOB, CUSTOMEREMAIL,
CUSTOMERPHONE, INVCOUNT)
VALUES
(0001, 'Yousef', 'Jarrar', '4342-5620-8563-5541', '27', '005845836@csusb.edu', '909-537-7266',
  10 );

INSERT INTO PERSPECTIVE
(PERSPECTIVETYPE, THEMETYPE)
VALUES
('1st Person', 'Future');

INSERT INTO RATING
(RATE, PERSPECTIVETYPE)
VALUES
(100, '1st Person');
