INSERT INTO Game
(InventoryID, gameMode, Developers, Rating, Platform, Genre, Publishers, Themes,
Perspective, Description, Availablity, InventoryCount, CustomerID, Title)
VALUES
(1, 'SP', 'Santa Monica STD', 96, 'PS4', 'Adventure', 'Sony ENT', 'Mythology', '3rd Person', 'Play as Kratos in the new 2018 Game', 'T', 10, 0001, 'God of War');

INSERT INTO PLATFORM
(PLATID, PLATNAME, PLATRATING, PLATDESC, PLATPRICE, INVENTORYID)
VALUES
( 1, 'PS4', 96, 'DEVELOPED BY SONY', 269, 1);

INSERT INTO gameMode
(modeType, inventoryID)
VALUES
('SP', 1);

INSERT INTO Developer
(DEVELOPER, DEVFIRST, DEVLAST, DEVCOMPANY, DEVDESC, INVENTORYID)
VALUES
('READY AT DAWN', 'SCOTT', 'ROGERS', 'SANTA MONICA STD', 'VIDEO GAME DESIGNER', 1);

INSERT INTO AVAILABLE
(AVAILGAME, INVENTORYID)
VALUES
('T',1);

INSERT INTO PUBLISHERS
(PUBFIRST, PUBLAST, PUBDESC, INVENTORYID, DEVELOPER)
VALUES
('Hirai', 'Kaz', 'CEO OF SONY ENT', 1, 'READY AT DAWN');

INSERT INTO INVCOUNT
(COUNT, AVAILGAME)
VALUES
(10, 'T');

INSERT INTO GENRE
(GENRETYPE, PLATID)
VALUES
('Adventure', 1 );

INSERT INTO THEMES
(THEMETYPE, GENRETYPE)
VALUES
('Mythology', 'Adventure');

INSERT INTO DESCRIPTION
(DESCRIPT, DESCPUBLISHER, DESCDEVELOPER, DESCGAME, INVENTORYID, DEVELOPER, PUBFIRST)
VALUES
('Table of Information', 'CEO OF SONY ENT', 'VIDEO GAME DESIGNER', 'Play as Kratos
  in the new 2018 Game', 1, 'READY AT DAWN', 'Hirai' );

INSERT INTO Customer
(CUSTOMERID, CUSTOMERFNAME, CUSTOMERLNAME, CUSTOMERCC, CUSTOMERDOB, CUSTOMEREMAIL,
CUSTOMERPHONE, INVCOUNT)
VALUES
(0001, 'Yousef', 'Jarrar', '4342-5620-8563-5541', '27', '005845836@csusb.edu', '909-537-7266',
  10 );

INSERT INTO PERSPECTIVE
(PERSPECTIVETYPE, THEMETYPE)
VALUES
('3rd Person', 'Mythology');

INSERT INTO RATING
(RATE, PERSPECTIVETYPE)
VALUES
(96, '3rd Person');
